### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by MTkatchouk** [CHERTS/zabbix_telegram_webhook#1]
Hi Mikhail!

Is it possible to add proxy support?

Many zabbix installations do not have direct access to the Internet, and especially to https://api.telegram.org.

P.S. Thank you for the Russian-language documentation! ;)

**Comment by cherts** [comment]
Sorry, but this is not yet possible.

The zabbix-server process uses the libcurl library to send requests, and unfortunately the zabbix developers did not take care of the ability to use the connection through the http proxy (CURLOPT_PROXY parameter in libcurl, see here in the code https://github.com/zabbix/zabbix/blob/master/src/libs/zbxembed/httprequest.c#L136).

---

Извините, но это пока невозможно сделать.

Процесс zabbix-server использует для отправки запросов библиотеку libcurl и к сожалению разработчики zabbix не позаботились о возможности использовать соединение через http прокси (параметр CURLOPT_PROXY в libcurl, примерно тут в коде https://github.com/zabbix/zabbix/blob/master/src/libs/zbxembed/httprequest.c#L136).

**Comment by cherts** [comment]
Also, the zabbix-server process does not accept the http_proxy environment variable for libcurl, in which you can specify a connection through a proxy.

---

Так же процесс zabbix-server не воспринимает переменную среды http_proxy для libcurl, в которой можно указать соединение через прокси.

**Comment by CHERTS** [comment]
I create [ZBXNEXT-5554 - Web hook through http proxy](https://support.zabbix.com/browse/ZBXNEXT-5554), vote for him please.

--

Я создал запрос на доработку [ZBXNEXT-5554 - Web hook through http proxy](https://support.zabbix.com/browse/ZBXNEXT-5554), проголосуйте за него пожалуйста.

**Comment by cherts** [comment]
I create [ZBXNEXT-5554 - Web hook through http proxy](https://support.zabbix.com/browse/ZBXNEXT-5554), vote for him please.

---

Я создал запрос на доработку [ZBXNEXT-5554 - Web hook through http proxy](https://support.zabbix.com/browse/ZBXNEXT-5554), проголосуйте за него пожалуйста.

**Comment by MTkatchouk** [comment]
Спасибо.
