### ISSUE TITLE
parse_mode следует указывать HTML большими буквами вместо html

### ISSUE THREAD

**Issue by maxgldn** [CHERTS/zabbix_telegram_webhook#2]
Михаил,

в шаблоне способа оповещения в забикс в параметре parse_mode следует указывать HTML большими буквами вместо html маленькими, также в 57 строке кода 
 if (params.parse_mode === 'html' || params.parse_mode === 'markdown' ) {&#13;
нужно проверять переменную на HTML вместо html.

Проверено на Zabbix 5.0.3

В остальном работает идеально, спасибо за ваш труд!

**Comment by cherts** [comment]
Исправил в https://github.com/CHERTS/zabbix_telegram_webhook/commit/6a402478d6d06d71f6aaa351983a73db07cc5a99

Спасибо.
